2903-halt-database-update: Updates config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -366,18 +366,19 @@ jobs:
           command: |
             cd database/changelog
             liquibase update > liquibase.out &
-            runFound=1
-            errorFound=1
-            while [ $runFound = 1 ] && [ $errorFound = 1 ];
+            runfound=1
+            errorfound=1
+            while [ $runfound = 1 ] && [ $errorfound = 1 ];
             do 
               grep Run: liquibase.out > /dev/null
-              runFound=$?
-              grep 'Unexpected error' liquibase.out > /dev/null
-              errorFound=$?
+              runfound=$?
+              grep "Unexpected error" liquibase.out > /dev/null
+              errorfound=$?
               sleep 1
             done
             updatecount=`grep Run: liquibase.out | tr -s " " | cut -d ' ' -f2 | tr -d '\n'`
-            if [ $errorFound = 0 ] || [ $updatecount = 0 ]; then
+            if [ $errorfound = 0 ] || [ $updatecount = 0 ]; then
+              echo "No changesets applied. Exiting job. errorfound ${errorfound}, updatecount ${updatecount}"
               circleci-agent step halt
             fi
       - node/install
